# Generated by Django 5.1.4 on 2025-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_card_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='office_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
