# Generated by Django 5.1.7 on 2025-04-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_card_office_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
